<?php

declare(strict_types=1);

namespace Made\Cms\App\Http\Controllers;

use Illuminate\Contracts\Container\BindingResolutionException;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller as BaseController;
use Made\Cms\Analytics\Models\Visit;
use Made\Cms\Models\Settings\WebsiteSetting;
use Made\Cms\Shared\Actions\GetControllerFromRouteable;
use Made\Cms\Shared\Models\Route;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\HttpException;

class Controller extends BaseController
{
    public function __construct(
        protected readonly WebsiteSetting $websiteSetting,
    ) {
        //
    }

    /**
     * Handles the invocation of the controller when the object is used as a callable.
     *
     * This method processes the incoming request by inspecting the URI and determining
     * the proper route to handle the request. If the URI is empty (representing the
     * root or landing page), it retrieves the landing page configuration. Otherwise,
     * it attempts to find a route that matches the URI. If no appropriate route is found,
     * the request is terminated with a 404 error.
     *
     * Once a valid route is identified, the associated controller is invoked to process
     * the request.
     *
     * @param  Request  $request  The incoming HTTP request containing the URI and other request data.
     * @return mixed The response generated by the invoked controller, which could be a view, JSON, or another HTTP response.
     *
     * @throws HttpException If the route does not exist or the landing page is not configured (404 error).
     * @throws BindingResolutionException If a controller for the resolved route cannot be instantiated.
     */
    public function __invoke(Request $request)
    {
        if ($this->websiteSetting->isOnline() === false) {
            abort(503);
        }

        $uri = $request->getRequestUri();

        if (strlen(trim($uri, '/')) === 0) {
            // Landing page
            $page = $this->websiteSetting->getLandingPage();

            if (empty($page) || empty($page->route)) {
                abort(404);
            }

            return $this->invokeController($request, $page->route);
        }

        $route = Route::query()
            ->where('route', '=', '/' . trim($uri, '/'))
            ->first();

        if (empty($route)) {
            abort(404);
        }

        return $this->invokeController($request, $route);
    }

    /**
     * Invokes the controller associated with the provided route and processes the request.
     *
     * This method determines the controller to handle the request based on the given route.
     * If no valid controller class can be derived from the route, a 404 error is triggered.
     * The method then invokes the controller and processes its response. If the request contains
     * a "visit" entity, it associates the visit with the route and updates its response code
     * based on the outcome of the controller's response.
     *
     * @param  Request  $request  The incoming HTTP request containing additional request data such as headers and parameters.
     * @param  Route|null  $route  The resolved route that determines the controller to be invoked, or null if no route is provided.
     * @return View|Response The response generated by the invoked controller, which could be a view or another HTTP response.
     *
     * @throws HttpException If no valid controller class can be determined from the route.
     * @throws BindingResolutionException If the required controller cannot be instantiated by the service container.
     */
    protected function invokeController(
        Request $request,
        ?Route $route = null
    ): View | Response {
        /** @var null|class-string<CmsRoutingContract> $class */
        $class = GetControllerFromRouteable::run($route);

        if (empty($class)) {
            abort(404);
        }

        $controller = app()->make($class);

        $response = $controller($request, $route->routeable);

        if ($request->has('visit')) {
            /** @var Visit $visit */
            $visit = $request->get('visit');

            if ($response instanceof View) {
                $visit->update([
                    'response_code' => 200,
                ]);
            } elseif ($response instanceof Response) {
                $visit->update([
                    'response_code' => $response->getStatusCode(),
                ]);
            }

            $visit->route()->associate($route);

            $visit->save();
            $visit->refresh();
        }

        return $response;
    }
}
